# Generated by Django 5.2.7 on 2025-11-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingtask",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="Exception traceback if task failed"
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="result_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL or path to processed image",
                max_length=500,
            ),
        ),
    ]
