name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Create test .env file
        run:  |
          echo "SECRET_KEY=test-secret-key-for-ci" > .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=localhost" >> .env

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run linter (ruff)
        run: uv run ruff check .

      - name: Run format check (ruff)
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run python manage.py test

      - name: Build Docker image
        run: docker build --tag remove-bg:latest .

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deployment Notification
        run: |
          echo "Tests passed! Render will auto-deploy from main branch."
          echo "Check Render dashboard for deployment status."
